# 应用服务 WEB 访问端口
server:
  port: 8080
# 应用名称
spring:
  application:
    name: spring-cloud-security
  # Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
  # Nacos认证信息
#  cloud:
#    nacos:
#      discovery:
#        username: nacos
#        password: nacos
#        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
#        server-addr: mse-6d50f4f0-p.nacos-ans.mse.aliyuncs.com:8848
#        # 注册到 nacos 的指定 namespace，默认为 public
#        namespace: public
  datasource:
    name: defaultDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC
    # 数据库用户名&密码：
    username: root
    password: 123456

swagger:
  show: true
