package top.yhl.cloud.common.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.yhl.cloud.common.model.HdBookmark;
import top.yhl.cloud.common.model.HdBookmarkExample;

public interface HdBookmarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_bookmark
     *
     * @mbg.generated
     */
    long countByExample(HdBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_bookmark
     *
     * @mbg.generated
     */
    int deleteByExample(HdBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_bookmark
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_bookmark
     *
     * @mbg.generated
     */
    int insert(HdBookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_bookmark
     *
     * @mbg.generated
     */
    int insertSelective(HdBookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_bookmark
     *
     * @mbg.generated
     */
    List<HdBookmark> selectByExample(HdBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_bookmark
     *
     * @mbg.generated
     */
    HdBookmark selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_bookmark
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HdBookmark record, @Param("example") HdBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_bookmark
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HdBookmark record, @Param("example") HdBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_bookmark
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HdBookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_bookmark
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HdBookmark record);
}