package com.yhl.cloud.generator.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import com.yhl.cloud.generator.model.HdFeedback;
import com.yhl.cloud.generator.model.HdFeedbackExample;

import javax.annotation.ManagedBean;

@Mapper
public interface HdFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_feedback
     *
     * @mbg.generated
     */
    long countByExample(HdFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_feedback
     *
     * @mbg.generated
     */
    int deleteByExample(HdFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_feedback
     *
     * @mbg.generated
     */
    int insert(HdFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_feedback
     *
     * @mbg.generated
     */
    int insertSelective(HdFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_feedback
     *
     * @mbg.generated
     */
    List<HdFeedback> selectByExample(HdFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_feedback
     *
     * @mbg.generated
     */
    HdFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_feedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HdFeedback record, @Param("example") HdFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_feedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HdFeedback record, @Param("example") HdFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HdFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hd_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HdFeedback record);
}