@startuml
'https://plantuml.com/sequence-diagram

autonumber

FeignInvocationHandler -> SynchronousMethodHandler: invoke > ((MethodHandler)this.dispatch.get(method)).invoke(args)
SynchronousMethodHandler --> Client: executeAndDecode() > this.com.netty.example.client.execute(request, this.options)

Client -> Default:execute() > convertResponse()
Default -> HttpURLConnection: getInputStream() > getInputStream0()  > connect() > plainConnect() > plainConnect0() > getNewHttpClient()
HttpURLConnection --> HttpClient: KeepAliveKey.get()
@enduml